// packages/@collabkit/react/src/components/comment/CurrentlyTyping.tsx
import React from 'react';
import type { Profile } from '@collabkit/core';
import { TypingIndicator } from './TypingIndicator';

// renders a list of users who are
// typing at the moment
export function CurrentlyTyping(props: {
  profiles: { [userId: string]: Profile };
  userId: string;
  isTyping?: { [userId: string]: boolean };
}) {
  const { profiles, isTyping, userId } = props;
  if (isTyping == null) {
    return null;
  }
  return (
    <>
      {Object.keys(isTyping).map((endUserId) =>
        endUserId !== userId && isTyping[endUserId] === true ? (
          <TypingIndicator key={`typing-${endUserId}`} profile={profiles[endUserId]} />
        ) : null
      )}
    </>
  );
}

// packages/@collabkit/vue/src/components/comment/CurrentlyTyping.vue
<script setup lang="ts">
import type { Profile } from '@collabkit/core';
import { computed } from '@vue/reactivity';
import TypingIndicator from './TypingIndicator.vue';

const props = defineProps<{
  profiles: { [userId: string]: Profile };
  userId: string;
  isTyping?: { [userId: string]: boolean };
}>();

const currentlyTyping = computed(() =>
  Object.keys(props.isTyping ?? {})
    .filter((endUserId) => endUserId !== props.userId)
    .map((endUserId) => [endUserId, props.profiles[endUserId]])
);
</script>

<template>
  <TypingIndicator
    v-for="[endUserId, profile] in currentlyTyping"
    :key="endUserId"
    :profile="profile"
  />
</template>
); }
