// packages/@collabkit/react/src/components/CommentList.tsx
import React from 'react';
import { Timeline } from '../constants';
import { styled } from '@stitches/react';
import equal from 'fast-deep-equal';
import { useTimeline } from '../hooks/useTimeline';
import { CommentGroup } from './CommentGroup';
import { commentListStyles } from '@collabkit/theme';

const StyledCommentList = styled('div', commentListStyles.list);

export const CommentList = React.memo(function CommentList(props: {
  timeline: Timeline;
  seenUntil?: string;
  workspaceId: string;
  userId: string;
  threadId: string;
  isPreview?: boolean;
  newIndicatorId?: string | null;
}) {
  const { threadId, workspaceId, timeline, newIndicatorId } = props;

  const { reactions, list } = useTimeline(timeline, props.seenUntil, props.userId);

  const groups = props.isPreview ? list.slice(0, 1) : list;

  if (!workspaceId) {
    return null;
  }

  return (
    <StyledCommentList>
      {groups.map((group, i) => {
        return (
          <CommentGroup
            key={i}
            group={group}
            userId={props.userId}
            reactions={reactions}
            workspaceId={workspaceId}
            threadId={threadId}
            isPreview={props.isPreview}
            newIndicatorId={newIndicatorId}
          />
        );
      })}
    </StyledCommentList>
  );
},
equal);

// packages/@collabkit/vue/src/components/CommentList.vue
<script setup lang="ts">
import { timelineUtils } from '@collabkit/core';
import type { Timeline } from '@collabkit/core';
import { commentListStyles } from '@collabkit/theme';
import { computed } from 'vue';
import CommentGroup from './CommentGroup.vue';
import { styled } from './styled';

const StyledCommentList = styled('div', commentListStyles.list);

const props = defineProps<{
  isTyping?: { [endUserId: string]: boolean };
  timeline: Timeline;
  seenUntil?: string;
  workspaceId: string;
  userId: string;
  threadId: string;
  isPreview?: boolean;
  newIndicatorId?: string | null;
}>();

const reactions = computed(() => timelineUtils.reactions(props.timeline));
const list = computed(() => timelineUtils.groupedMessages(props.timeline));
const groups = computed(() => (props.isPreview ? list.value.slice(0, 1) : list.value));
</script>

<template>
  <StyledCommentList>
    <CommentGroup
      v-for="group in groups"
      :group="group"
      :userId="userId"
      :seenUntil="seenUntil"
      :reactions="reactions"
      :workspaceId="workspaceId"
      :threadId="threadId"
      :isPreview="isPreview"
      :newIndicatorId="newIndicatorId"
    />
  </StyledCommentList>
</template>
