// packages/@collabkit/react/src/components/Provider.tsx
import React, { useEffect, useLayoutEffect, useState } from 'react';
import { actions } from '../actions';
import { IdentifyProps, MentionProps, Store } from '../constants';
import { Events, createEvents } from '../events';
import { AppContext } from '../hooks/useAppContext';
import { createStore } from '../store';
import { FirebaseSync } from '../sync';
import { createThemes, DeepPartial, Theme } from './UIKit';
import merge from 'lodash.merge';

const systemDarkMode =
  window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;

// Enable using multiple isolated App
// instances in the same page.
export function CollabKitProvider({
  children,
  colorScheme,
  theme,
  ...config
}: {
  appId: string;
  apiKey: string;
  workspace: { id: string; name?: string };
  user: IdentifyProps;
  mentionableUsers: MentionProps;
  children: React.ReactNode;
  colorScheme?: 'light' | 'dark' | 'auto';
  theme?: DeepPartial<Theme>;
  readOnly?: boolean;
  mode?: 'demo';
  _demoStore?: Store;
}) {
  const [context, setContext] = useState<{ store: Store; events: Events } | null>(null);

  const { darkTheme, lightTheme } = createThemes(theme);

  const themes = {
    dark: darkTheme,
    light: lightTheme,
    auto: systemDarkMode ? darkTheme : lightTheme,
  };

  useLayoutEffect(() => {
    const sync = new FirebaseSync();
    const store = config._demoStore ?? createStore(config, sync);
    const events = createEvents(store);
    actions.monitorConnection(store, events);
    setContext({ store, events });
    return () => {
      events.onDestroy();
    };
  }, [config.apiKey]);

  useEffect(() => {
    if (context) {
      document.addEventListener('keydown', context.events.onKeyDown);
      return () => {
        document.removeEventListener('keydown', context.events.onKeyDown);
      };
    }
  }, [context]);

  if (!context) {
    return null;
  }

  const baseTheme = themes[colorScheme ?? 'auto'];

  return (
    <AppContext.Provider
      value={{
        store: context.store,
        events: context.events,
        workspaceId: config.workspace.id,
        theme: theme ? merge(baseTheme, theme) : baseTheme,
      }}
    >
      <span className={baseTheme.className.toString()}>{children}</span>
    </AppContext.Provider>
  );
}

// packages/@collabkit/vue/src/components/Provider.vue
<script setup lang="ts">
import { StoreKey, ThemeKey } from '../constants';
import { createVueStore } from '../stores/store';
import { actions, createEvents, FirebaseSync, initFirebase } from '@collabkit/client';
import type { Config, DeepPartial, Store, UserProps, WorkspaceProps } from '@collabkit/core';
import type { Theme } from '@collabkit/theme';
import { onBeforeUnmount, onMounted, provide } from 'vue';
import { useTheme } from '../composables/useTheme';
import { func } from 'prop-types';

initFirebase();

const props = defineProps<{
  colorScheme?: 'light' | 'dark' | 'auto';
  theme?: DeepPartial<Theme>;

  appId?: string;
  token?: string;

  apiKey?: string;
  user?: UserProps;
  workspace?: WorkspaceProps;
}>();

const currentTheme = useTheme(props);
provide(ThemeKey, currentTheme);

const store = createVueStore() as Store;
actions.init(store, props as Config, new FirebaseSync());
const events = createEvents(store);
provide(StoreKey, { store, events });

onMounted(() => {
  actions.monitorConnection(store, events);
});

// Set up keydown listener
onMounted(() => {
  document.addEventListener('keydown', onKeyDown);
});
onBeforeUnmount(() => {
  document.removeEventListener('keydown', onKeyDown);
});
function onKeyDown(e: KeyboardEvent) {
  events.onKeyDown(e);
}
</script>

<template>
  <span :className="currentTheme.className.toString()"><slot /></span>
</template>
