// packages/@collabkit/react/src/components/ScrollableCommentList.tsx
import { useCallback, useEffect, useRef } from 'react';
import {
  ScrollAreaCorner,
  ScrollAreaRoot,
  ScrollAreaScrollbar,
  ScrollAreaThumb,
  ScrollAreaViewport,
} from './ScrollArea';
import React from 'react';
import { Timeline } from '../constants';
import equal from 'fast-deep-equal';
import { useTimeline } from '../hooks/useTimeline';
import { CommentList } from './CommentList';
import { useNewIndicator } from './NewIndicator';

export const ScrollableCommentList = React.memo(function ScrollableCommentList(props: {
  timeline: Timeline;
  workspaceId: string;
  userId: string;
  threadId: string;
  seenUntil?: string;
  isPreview?: boolean;
}) {
  const { workspaceId, userId, seenUntil } = props;

  const scrollRef = useRef<HTMLDivElement>(null);
  const { timeline } = props;

  const { messageEvents, reactionEvents } = useTimeline(timeline);

  const newIndicatorId = useNewIndicator({ messageEvents, userId, seenUntil });

  // todo this needs reworking anyway to show a 'new messages' button
  useEffect(() => {
    scrollRef.current?.scrollTo(0, scrollRef.current?.scrollHeight);
  }, [
    messageEvents.length,
    // did react to last message
    reactionEvents[reactionEvents.length - 1]?.parentId ===
      messageEvents[messageEvents.length - 1]?.id,
    // check that all profiles are loaded
    messageEvents.every((event) => event.hasProfile),
    newIndicatorId,
  ]);

  const handleScroll = useCallback((e: React.SyntheticEvent) => {
    // todo use this to load more comments when scrolling to top / near the top
  }, []);

  if (!workspaceId) {
    return null;
  }

  return (
    <ScrollAreaRoot>
      <ScrollAreaViewport onScroll={handleScroll} ref={scrollRef}>
        <CommentList
          newIndicatorId={newIndicatorId}
          seenUntil={props.seenUntil}
          threadId={props.threadId}
          userId={props.userId}
          workspaceId={workspaceId}
          isPreview={props.isPreview}
          timeline={timeline}
        />
      </ScrollAreaViewport>
      <ScrollAreaScrollbar orientation="vertical">
        <ScrollAreaThumb />
      </ScrollAreaScrollbar>
      <ScrollAreaCorner />
    </ScrollAreaRoot>
  );
},
equal);

// packages/@collabkit/vue/src/components/ScrollableCommentList.vue
<script setup lang="ts">
import { nextTick, onMounted, ref, computed, watch } from 'vue';
import { timelineUtils } from '@collabkit/core';
import type { Profile, Timeline } from '@collabkit/core';
import { useNewIndicator } from '../composables/useNewIndicator';
import {
  ScrollAreaRoot,
  ScrollAreaViewport,
  ScrollAreaScrollbar,
  ScrollAreaThumb,
  ScrollAreaCorner,
} from './ScrollArea';
import CommentList from './CommentList.vue';

const props = defineProps<{
  isTyping?: { [endUserId: string]: boolean };
  timeline: Timeline;
  workspaceId: string;
  userId: string;
  threadId: string;
  seenUntil?: string;
  isPreview?: boolean;
}>();

const timelineEvents = computed(() => ({
  messageEvents: timelineUtils.messageEvents(props.timeline),
  reactionEvents: timelineUtils.reactionEvents(props.timeline),
}));

const newIndicatorId = useNewIndicator(props, timelineEvents);

const viewport = ref<{ element: HTMLDivElement } | null>(null);
const scrollDependencies = computed(() => {
  const { messageEvents, reactionEvents } = timelineEvents.value;
  return [
    viewport,
    messageEvents.length,
    // did react to last message
    reactionEvents[reactionEvents.length - 1]?.parentId ===
      messageEvents[messageEvents.length - 1]?.id,
    // check that all profiles are loaded
    messageEvents.every((event) => event.hasProfile),
    newIndicatorId,
  ];
});
watch(scrollDependencies, () => {
  if (viewport.value) {
    const { element } = viewport.value;
    nextTick(() => {
      element.scrollTop = element.scrollHeight;
    });
  }
});
</script>

<template>
  <ScrollAreaRoot>
    <ScrollAreaViewport ref="viewport">
      <CommentList
        :newIndicatorId="newIndicatorId"
        :seenUntil="seenUntil"
        :isTyping="isTyping"
        :threadId="threadId"
        :userId="userId"
        :workspaceId="workspaceId"
        :isPreview="isPreview"
        :timeline="timeline"
      />
    </ScrollAreaViewport>
    <ScrollAreaScrollbar orientation="vertical">
      <ScrollAreaThumb />
    </ScrollAreaScrollbar>
    <ScrollAreaCorner />
  </ScrollAreaRoot>
</template>
