// packages/@collabkit/vue/src/components/composer/ComposerSendButton.vue
<script setup lang="ts">
import { ArrowUp } from '../icons';

import { sendButtonStyles } from '@collabkit/theme';
import { styled } from '../styled';
import { inject } from 'vue';
import { ThemeKey } from '../../constants';
import { useEvents } from '../../composables/useEvents';
import type { ProvidedTheme } from '../../types';

const props = defineProps<{
  bodyLength: number;
  workspaceId: string;
  threadId: string;
  type: 'icon' | 'text';
}>();

const StyledComposerSendButton = styled('div', sendButtonStyles.button);
const StyledComposerSendButtonIcon = styled(ArrowUp, sendButtonStyles.icon);

const theme = inject<ProvidedTheme>(ThemeKey)!;
const events = useEvents();

function onClick() {
  if (props.bodyLength > 0) {
    events.onSend(props.workspaceId, props.threadId);
  }
}
</script>

<template>
  <div :style="{ display: 'flex', alignItems: 'flex-start', marginTop: '6px' }">
    <StyledComposerSendButton
      :disabled="bodyLength === 0"
      @click="onClick"
      title="Send"
      :type="props.type"
    >
      <StyledComposerSendButtonIcon
        v-if="type === 'icon'"
        :size="13"
        :color="theme.colors.composerButtonIconColor.toString()"
        weight="bold"
      />
      <span v-if="type === 'text'">Comment</span>
    </StyledComposerSendButton>
  </div>
</template>

// packages/@collabkit/react/src/components/composer/ComposerSendButton.tsx
import { sendButtonStyles } from '@collabkit/theme';
import { styled } from '@stitches/react';
import React from 'react';
import { useSnapshot } from 'valtio';
import { useApp } from '../../hooks/useApp';
import { useThreadContext } from '../../hooks/useThreadContext';
import { Button } from '../Button';
import { ArrowUp } from '../icons';

const StyledComposerSendButtonIcon = styled(ArrowUp, sendButtonStyles.icon);

export function ComposerSendButton() {
  const { store, events, theme } = useApp();
  const { threadId } = useThreadContext();
  const { workspaceId, workspaces } = useSnapshot(store);

  if (!workspaceId) {
    return null;
  }
  const workspace = workspaces[workspaceId];

  const composer = workspace ? workspace.composers[threadId] : null;

  const bodyLength = composer?.$$body.trim().length ?? 0;

  return (
    <Button
      onPointerDown={(e) => {
        events.onSend(workspaceId, threadId);
      }}
      type="primary"
      icon={
        <StyledComposerSendButtonIcon
          size={13}
          color={theme.colors.composerButtonIconColor.toString()}
          weight="bold"
        />
      }
      disabled={bodyLength === 0}
    />
  );
}
