// packages/@collabkit/vue/src/components/composer/Composer.vue
<script setup lang="ts">
import { computed } from 'vue';
import { composerStyles } from '@collabkit/theme';
import { styled } from '../styled';
import { useStore } from '../../composables/useStore';

const props = defineProps<{
  workspaceId: string;
  threadId: string;
  userId: string;
  placeholder: string;
  autoFocus?: boolean;
}>();

const ComposerRoot = styled('div', composerStyles.root);

const store = useStore();

const composer = computed(() =>
  store.workspaces[props.workspaceId]
    ? store.workspaces[props.workspaceId].composers[props.threadId]
    : null
);
</script>

<template>
  <div>
    <div id="#mentions" :style="{ position: 'relative' }"></div>
    <ComposerRoot v-if="composer != null">
      <slot></slot>
    </ComposerRoot>
  </div>
</template>

// packages/@collabkit/react/src/components/composer/Composer.tsx
import React from 'react';

import { styled } from '@stitches/react';

import { composerStyles } from '@collabkit/theme';

const StyledComposerRoot = styled('div', composerStyles.root);

export function Composer(props: {
  workspaceId: string;
  threadId: string;
  userId: string;
  hideAvatar?: boolean;
  children: React.ReactNode;
}) {
  return (
    <>
      <div id="mentions" style={{ position: 'relative' }} />
      <StyledComposerRoot>{props.children}</StyledComposerRoot>
    </>
  );
}
