// packages/@collabkit/vue/src/components/composer/SendButton.vue
<script setup lang="ts">
import { ArrowUp } from '../icons';

import { sendButtonStyles, type Theme } from '@collabkit/theme';
import { styled } from '../styled';
import { inject } from 'vue';
import { ThemeKey } from '../../constants';
import { useEvents } from '../../composables/useEvents';

const props = defineProps<{
  bodyLength: number;
  workspaceId: string;
  threadId: string;
}>();

const StyledComposerSendButton = styled('button', sendButtonStyles.button);
const StyledComposerSendButtonIcon = styled(ArrowUp, sendButtonStyles.icon);

const theme = inject<Theme>(ThemeKey)!;
const events = useEvents();

function onClick() {
  if (props.bodyLength > 0) {
    events.onSend(props.workspaceId, props.threadId);
  }
}
</script>

<template>
  <StyledComposerSendButton :disabled="bodyLength === 0" @click="onClick" title="Post">
    <StyledComposerSendButtonIcon
      :size="13"
      :color="theme.colors.composerButtonIconColor.toString()"
      weight="bold"
    />
  </StyledComposerSendButton>
</template>

// packages/@collabkit/react/src/components/composer/SendButton.tsx
import * as Tooltip from '../Tooltip';
import React from 'react';
import { ArrowUp } from '../icons';
import { useApp } from '../../hooks/useApp';
import { styled } from '@stitches/react';
import { sendButtonStyles } from '@collabkit/theme';

const StyledComposerSendButton = styled(Tooltip.Trigger, sendButtonStyles.button);
const StyledComposerSendButtonIcon = styled(ArrowUp, sendButtonStyles.icon);

export function SendButton(props: { bodyLength: number; workspaceId: string; threadId: string }) {
  const { events, theme } = useApp();
  const { bodyLength, workspaceId, threadId } = props;
  return (
    <Tooltip.Root>
      <StyledComposerSendButton
        disabled={bodyLength === 0}
        onClick={() => {
          if (bodyLength > 0) {
            events.onSend(workspaceId, threadId);
          }
        }}
      >
        <StyledComposerSendButtonIcon
          size={13}
          color={theme.colors.composerButtonIconColor.toString()}
          weight="bold"
        />
      </StyledComposerSendButton>
      <Tooltip.Content>
        Post
        <Tooltip.Arrow />
      </Tooltip.Content>
    </Tooltip.Root>
  );
}
