// examples/demo-vue/src/Home.vue
<script setup lang="ts">
import { Thread, useUnreadCount } from '@collabkit/vue';
import { computed } from 'vue';
import { useTitle } from '@vueuse/core';

const threadId = 'your-thread-id';
const unreadCount = useUnreadCount({ threadId });
const title = computed(() =>
  unreadCount.value > 0 ? `CollabKit Vue (${unreadCount.value})` : 'CollabKit Vue'
);
useTitle(title);
</script>

<template>
  <Thread :threadId="threadId" autoFocus composerPrompt="Write a comment" />
</template>

<style scoped>
main {
  position: fixed;
  inset: 0;
}
</style>

// examples/demo/src/Home.tsx
import { Thread, useUnreadCount } from '@collabkit/react';
import { useDocumentTitle } from './hooks/useDocumentTitle';

export function Home() {
  const threadId = 'new-your-thread-id2';

  const unreadCount = useUnreadCount({ threadId });
  const unread = unreadCount > 0 ? ` (${unreadCount})` : '';
  useDocumentTitle(`CollabKit Demo${unread}`);

  return (
    <Thread
      style={{ position: 'fixed', inset: 0 }}
      autoFocus={true}
      info={{ name: 'Demo thread' }}
      showHeader={true}
      threadId={threadId}
    />
  );
}
