// packages/@collabkit/vue/src/components/comment/MessageHeader.vue
<script setup lang="ts">
import { formatRelative } from 'date-fns';
import { messageHeaderStyles } from '@collabkit/theme';
import { computed } from 'vue';
import { styled } from '../styled';

const Name = styled('div', messageHeaderStyles.name);
const StyledMessageTimestamp = styled('span', messageHeaderStyles.timestamp);

const props = defineProps<{ name: string; createdAt: number }>();

const timestamp = computed(() =>
  formatRelative(props.createdAt, +Date.now())
    .replace(/yesterday at (.*)/, 'yesterday')
    .replace('today at', '')
    .replace(/(last Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday) .*/, '$1')
);
</script>

<template>
  <Name>
    {{ name }}{{ ' ' }}
    <StyledMessageTimestamp>
      {{ timestamp }}
    </StyledMessageTimestamp>
  </Name>
</template>

// packages/@collabkit/react/src/components/comment/MessageHeader.tsx
import { styled } from '@stitches/react';
import { formatRelative } from 'date-fns';
import React from 'react';
import { messageHeaderStyles } from '@collabkit/theme';

const Name = styled('div', messageHeaderStyles.name);
const StyledMessageTimestamp = styled('span', messageHeaderStyles.timestamp);

export function MessageHeader(props: { name: string; createdAt: number }) {
  return (
    <Name>
      {props.name}{' '}
      <StyledMessageTimestamp>
        {formatRelative(props.createdAt, +Date.now())
          .replace(/yesterday at (.*)/, 'yesterday')
          .replace('today at', '')
          .replace(/(last Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday) .*/, '$1')}
      </StyledMessageTimestamp>
    </Name>
  );
}
