// packages/@collabkit/vue/src/components/comment/TypingIndicator.vue
<script setup lang="ts">
import type { Profile } from '@collabkit/core';
import { typingIndicatorStyles } from '@collabkit/theme';
import { styled } from '../styled';
import { HStack } from '../UIKit';
import { StyledCommentContainer, StyledCommentMessage } from './StyledComment';

const StyledIsTypingText = styled('span', typingIndicatorStyles.typingText);

defineProps<{ profile: Profile }>();
</script>

<template>
  <StyledCommentContainer>
    <HStack>
      <StyledCommentMessage :profileIndent="true">
        <StyledIsTypingText>
          <span>{{ profile.name || profile.email }}</span> is typing...
        </StyledIsTypingText>
      </StyledCommentMessage>
    </HStack>
  </StyledCommentContainer>
</template>

// packages/@collabkit/react/src/components/comment/TypingIndicator.tsx
import React from 'react';
import { styled } from '@stitches/react';
import { Profile } from '../../constants';
import { StyledCommentContainer, StyledCommentMessage } from '../Comment';
import { typingIndicatorStyles } from '@collabkit/theme';

// renders a list of users who are
// typing at the moment
export function CurrentlyTyping(props: {
  profiles: { [userId: string]: Profile };
  userId: string;
  isTyping?: { [userId: string]: boolean };
}) {
  const { profiles, isTyping, userId } = props;
  return isTyping ? (
    <>
      {Object.keys(isTyping).map((endUserId) =>
        // skip current user
        endUserId !== userId ? (
          isTyping?.[endUserId] === true ? (
            <TypingIndicator key={`typing-${endUserId}`} profile={profiles[endUserId]} />
          ) : null
        ) : null
      )}
    </>
  ) : null;
}

const StyledIsTypingText = styled('span', typingIndicatorStyles.typingText);

function TypingIndicator(props: { profile: Profile }) {
  return (
    <StyledCommentContainer>
      <div style={{ display: 'flex', flexDirection: 'column', marginLeft: 32 }}>
        <StyledCommentMessage>
          <StyledIsTypingText>
            <span>{props.profile.name || props.profile.email}</span> is typing...
          </StyledIsTypingText>
        </StyledCommentMessage>
      </div>
    </StyledCommentContainer>
  );
}
