// packages/@collabkit/vue/src/components/Thread/Thread.vue
<script setup lang="ts">
import ThreadRoot from './ThreadRoot.vue';
import ThreadHeader from './ThreadHeader.vue';
import Scrollable from '../Scrollable.vue';
import CommentList from '../CommentList.vue';
import { Composer } from '../Composer';
import type { ThreadInfo } from '@collabkit/core';

defineProps<{
  threadId: string;
  info?: Omit<ThreadInfo, 'defaultSubscribers'>;
  defaultSubscribers?: string[];
  showHeader?: boolean;
  autoFocus?: boolean;
  hideComposer?: boolean;
  hideResolveButton?: boolean;
}>();
</script>

<template>
  <ThreadRoot v-bind="$props">
    <ThreadHeader v-if="showHeader">Comments</ThreadHeader>
    <Scrollable autoScroll="bottom">
      <CommentList :hideResolveButton="hideResolveButton" />
    </Scrollable>
    <Composer v-if="!hideComposer" />
  </ThreadRoot>
</template>

// packages/@collabkit/pro-theme-latitude/src/components/Thread.tsx
import React from 'react';
import {
  CommentList,
  ComposerContentEditable,
  ComposerEditor,
  ComposerInput,
  ComposerPlaceholder,
  ComposerRoot,
  ComposerTypingIndicator,
  ProfileAvatar,
  Scrollable,
  ThreadHeader,
  ThreadProps,
  ThreadRoot,
  useIsAuthenticated,
} from '@collabkit/react';

export function Thread(props: ThreadProps & { maxHeight?: number }) {
  const isAuthenticated = useIsAuthenticated();

  if (!isAuthenticated) {
    return null;
  }

  return (
    <ThreadRoot {...props}>
      {props.showHeader && <ThreadHeader>Comments</ThreadHeader>}
      <Scrollable autoScroll="bottom" maxHeight={props.maxHeight}>
        <CommentList />
      </Scrollable>
      {props.hideComposer ? null : (
        <ComposerRoot>
          <ProfileAvatar />
          <ComposerEditor>
            <ComposerInput
              autoFocus={props.autoFocus}
              placeholder={<ComposerPlaceholder>{props.placeholder}</ComposerPlaceholder>}
              contentEditable={<ComposerContentEditable />}
            />
          </ComposerEditor>

          <ComposerTypingIndicator />
        </ComposerRoot>
      )}
    </ThreadRoot>
  );
}
