// packages/@collabkit/vue/src/components/Profile/Avatar.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { getProfileColor } from '@collabkit/colors';
import type { Profile } from '@collabkit/core';
import * as styles from '../../theme/components/Profile.css';

const props = defineProps<{
  profile: Profile;
}>();

const didError = ref(false);
const style = computed(() =>
  props.profile.color
    ? {
        backgroundColor: getProfileColor(props.profile.color),
      }
    : undefined
);

function onError() {
  didError.value = true;
}
</script>

<template>
  <div v-if="didError || !profile.avatar" :class-name="styles.avatar" :style="style">
    {{ profile.name?.charAt(0) }}
  </div>
  <img v-else :class-name="styles.avatar" :src="profile.avatar" @error="onError" />
</template>

// packages/@collabkit/react/src/components/Avatar.tsx
import React, { useState } from 'react';
import { getShade } from '@collabkit/colors';
import type { Profile } from '../constants';
import { avatarStyles } from '@collabkit/theme';
import { styled } from '@stitches/react';

export const StyledAvatar = styled('img', avatarStyles.avatar);
export const StyledDefaultAvatar = styled('div', avatarStyles.avatar);

export function Avatar({ profile, style }: { profile: Profile; style?: React.CSSProperties }) {
  const [didError, setDidError] = useState(false);

  return didError || !profile.avatar ? (
    <StyledDefaultAvatar
      style={{
        ...style,
        ...(profile.color
          ? {
              backgroundColor: getShade(profile.color, 9),
            }
          : {}),
      }}
    >
      {profile.name?.charAt(0)}
    </StyledDefaultAvatar>
  ) : (
    <StyledAvatar src={profile.avatar!} onError={() => setDidError(true)} style={style} />
  );
}
