// packages/@collabkit/vue/src/components/CommentGroup.vue
<script setup lang="ts">
import type { Event, CommentType, Profile, WithID } from '@collabkit/core';
import Comment from './Comment.vue';
import Target from './Target.vue';
import { computed } from '@vue/reactivity';

const props = defineProps<{
  group: WithID<Event>[];
  profiles: { [profileId: string]: Profile };
  reactions: { [parentId: string]: { [createdById: string]: Event } };
  workspaceId: string;
  threadId: string;
  isPreview?: boolean;
}>();

const comments = computed(() => (props.isPreview ? props.group.slice(0, 1) : props.group));

function getCommentType(group: Event[], index: number): CommentType {
  let type: CommentType = 'default';

  if (group.length > 1) {
    type = 'inline';

    if (index === 0) {
      type = 'inline-start';
    }

    if (index === group.length - 1) {
      type = 'inline-end';
    }
  }

  return type;
}
</script>

<template>
  <Target
    v-for="(event, index) in comments"
    :target="{ type: 'comment', eventId: event.id, workspaceId, threadId }"
  >
    <Comment
      :id="event.id"
      :event="event"
      :reactions="reactions[event.id] ?? {}"
      :type="getCommentType(group, index)"
      :timestamp="event.createdAt"
      :key="`event-${event.id}`"
      :body="event.body"
      :profile="profiles[event.createdById]"
      :isPreview="isPreview"
    />
  </Target>
</template>

// packages/@collabkit/react/src/components/CommentGroup.tsx
import React from 'react';
import { Comment } from './Comment';
import { Event, CommentType, Profile, WithID } from '../constants';
import { Target } from './Target';

export function CommentGroup(props: {
  group: WithID<Event>[];
  profiles: { [profileId: string]: Profile };
  reactions: { [parentId: string]: { [createdById: string]: Event } };
  workspaceId: string;
  threadId: string;
  rootRef: React.RefObject<HTMLDivElement>;
  isPreview?: boolean;
}) {
  const { group, profiles, reactions, workspaceId, threadId } = props;

  return (
    <div>
      {(props.isPreview ? group.slice(0, 1) : group).map((event, j) => {
        let type: CommentType = 'default';

        if (group.length > 1) {
          type = 'inline';

          if (j === 0) {
            type = 'inline-start';
          }

          if (j === group.length - 1) {
            type = 'inline-end';
          }
        }

        const profile = profiles[event.createdById];

        return (
          <Target
            key={event.id}
            target={{ type: 'comment', eventId: event.id, workspaceId, threadId }}
          >
            <Comment
              id={event.id}
              event={event}
              reactions={reactions[event.id]}
              type={type}
              timestamp={event.createdAt}
              key={`event-${event.id}`}
              rootRef={props.rootRef}
              body={event.body}
              profile={profile}
              isPreview={props.isPreview}
            />
          </Target>
        );
      })}
    </div>
  );
}
